services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./backend:/var/www/html
        ports:
            - "9000:9000"
        depends_on:
            - postgres

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./backend:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

#    postgres:
#        image: postgres:16
#        environment:
#            POSTGRES_DB: lets-go
#            POSTGRES_USER: postgres
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - "5432:5432"
#        volumes:
#            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
